### ISSUE TITLE
Help - NSMenuItem.SeparatorItem shows full height

### ISSUE THREAD

**Issue by ivancitin** [xamarin/mac-samples#100]
Taking the example:
https://github.com/xamarin/mac-samples/blob/0151e412335789c392cb2e834ff274135f060731/ExtensionSamples/FinderSyncExtension/FinderSync.cs#L29

And adding this lines right after
```
menu.AddItem(NSMenuItem.SeparatorItem);
menu.AddItem("Second Item", new ObjCRuntime.Selector("getURL:"), string.Empty);
```

Places a separator item, but it shows with the full height of a regular menu item, instead of a thin line as expected.

Has anyone experienced this, is there something i can do to fix it.

I'm using Xamarin.Mac version 4.2.1.29, on a 10.12 Mac.

<img width="365" alt="finder-extension-separator-item" src="https://user-images.githubusercontent.com/28026680/44113901-6fce7734-9fbe-11e8-8064-32a4c2b8b46e.png">

**Comment by bradumbaugh** [comment]
Hi @ivancitin, I was able to reproduce this. I then tried a couple of things:

1. I created (with Xamarin.Mac) a simple menu bar app and added a separator to its menu; this _did_ show the horizontal line, as expected.
2. I used Xcode to create a macOS app, and added a Finder Sync extension target to it. Then, in the Finder Sync extension's auto-generated `menuForKind`  method, I added a separator and another menu item, and it shows also as you have it listed above – with a space.

I also came across a Stack Overflow post from an Objective-C developer asking the same question: https://stackoverflow.com/questions/42537343/how-to-create-logical-groups-inside-a-context-menu-mac-os (another relevant Stack Overflow post here: https://stackoverflow.com/questions/32692909/findersync-issues-with-sidebar-icon-toolbar-icon-and-context-menu).

Unfortunately, for Finder Sync extensions, it looks like this may be the expected behavior. I'm going to close this issue, but please comment if you find an alternative. Thank you!
