### ISSUE TITLE
NeHeLessons2 no rendering

### ISSUE THREAD

**Issue by xdinos** [xamarin/mac-samples#117]

**Comment by dalexsoto** [comment]
Hello!

Could you please be more specific in the issue you are reporting?

Thanks!

**Comment by xdinos** [comment]
Yes sorry, you are right,
If you build and run the sample there isn't any output just the dark(gray) background of the window.

**Comment by xdinos** [comment]
Visual Studio for Mac 8.1, macOS Mojave 10.14.5, XCode 10.2.1

**Comment by LarryTheCoderGuy** [comment]
Same.. no rendering.

**Comment by sungiant** [comment]
Same for all of the OpenGL mac samples...  Mojave 10.14.6 XCode 10.3

**Comment by sungiant** [comment]
I think this issue should be changed to a `bug` instead of a `question` and its title updated to something more generic such as "Rendering broken for all OpenTK samples".

I also think this issue is likely in need some form of escalation as the root of issue is not problem with the samples themselves (there have been no breaking changes that the samples have failed to incorporate - they should work as is) but rather a problem with the underlying libraries.

It is possible that this issue could be due to an incompatibility at the Xamarin library level introduced by the changes from Mojave or the latest XCode.

**Comment by sungiant** [comment]
Just checked the `xamarin-macios` repo and found the same issue listed: https://github.com/xamarin/xamarin-macios/issues/4959

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
