### ISSUE TITLE
`read: -p no coprocess error output in terminal` when running F# solution in Xamarin Mac

### ISSUE THREAD

**Issue by jacqueline-homan** [xamarin/mac-samples#7]
![nocoprocess](https://cloud.githubusercontent.com/assets/3537889/9507508/ac579e2c-4c1c-11e5-9081-bc6c5f7e73e2.png)
![nocoprocess2](https://cloud.githubusercontent.com/assets/3537889/9507514/bd25cd32-4c1c-11e5-82e9-d590323b7cc0.png)

And for a sanity check....
![xbuild](https://cloud.githubusercontent.com/assets/3537889/9507526/e8c15aec-4c1c-11e5-984e-c4c23a48cae7.png)
![xbuild2](https://cloud.githubusercontent.com/assets/3537889/9507530/f141f1e0-4c1c-11e5-9f56-62fc45666976.png)

And I even made sure my gcc compiler was installed...

![gcc](https://cloud.githubusercontent.com/assets/3537889/9507538/013e2a50-4c1d-11e5-8e83-a84442d3cdb4.png)

**Comment by olegoid** [comment]
Hello @jacqueline-homan, thanks for reporting this issue. We can no longer reproduce it with both headless builds and Xamarin Studio.

I'm closing this issue for now. Let us know if we missed some details.

**Comment by matthewmccullough** [comment]
## Situation
There's a `read -p 'Press any key to continue...'` being given to the shell by Visual Studio, asking the user to signal if they want to continue so that the console window doesn't close right away.  

## Problem
[This is not a cross-shell compatible way of prompting the user](https://unix.stackexchange.com/a/198374).

## Complication
If the user has their system shell set to Zsh, this will fail with the `read: -p no coprocess` error message.

## Action
I recommend something like `printf 'Press any key to continue...';read ans`

## Verification
I've toggled my shell to Bash and the same flow causes no error message.  I toggled back to Zsh as my default shell and was able to reproduce it.  This was reproducible with [Visual Studio for Mac 7.0 (build 3146)](https://www.visualstudio.com/vs/visual-studio-mac/).

**Comment by tfoldi** [comment]
My default shell is also zsh and this issue is pretty annoying, please fix it
